# Generated by Django 5.2 on 2025-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_email', models.EmailField(max_length=254)),
                ('User_gender', models.CharField(max_length=50)),
                ('User_image', models.ImageField(upload_to='images/')),
                ('User_document', models.FileField(upload_to='file/')),
                ('User_password', models.CharField(max_length=50)),
            ],
        ),
    ]
