# Generated by Django 5.2 on 2025-05-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
                ('Admin_email', models.EmailField(max_length=254)),
                ('Admin_gender', models.CharField(max_length=50)),
                ('Admin_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Admin_document', models.FileField(blank=True, null=True, upload_to='file/')),
                ('Admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_email', models.EmailField(max_length=254)),
                ('User_gender', models.CharField(max_length=50)),
                ('User_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('User_document', models.FileField(blank=True, null=True, upload_to='file/')),
                ('User_password', models.CharField(max_length=50)),
                ('User_contact', models.IntegerField()),
                ('User_joindate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.TextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
