# Generated by Django 5.2 on 2025-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.TextField(max_length=200),
        ),
    ]
