# Generated by Django 5.2 on 2025-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_document',
            field=models.FileField(blank=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
