# Generated by Django 5.2 on 2025-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='User_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='User_joindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
