# Generated by Django 5.2 on 2025-05-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_user_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
